# Generated by Django 5.1.5 on 2025-11-02 08:49

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prod_app', models.TextField(default='')),
                ('category', models.CharField(choices=[('curd', 'Curd'), 
                    ('milk', 'Milk'), ('lassi', 'Lassi'), ('milkshake', 'Milkshake'), 
                    ('paneer', 'Panner'), ('ghee', 'Ghee'), ('cheese', 'Cheese'), 
                    ('icecream', 'Ice-cream')], max_length=10)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
