# Generated by Django 5.1.4 on 2025-12-23 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arnob', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Mymensingh', 'Mymensingh'), ('Gazipur', 'Gazipur'), ('Sherpur', 'Sherpur'), 
                    ('Netrokuna', 'Netrokuna'), ('Jamalpur', 'Jamalpur'), ('Tangail', 'Tangail'), ('Shirajgonj', 'Shirajgonj'), 
                    ('Dhaka', 'Dhaka'), ('Kishoregonj', 'Kishoregonj'), ('Sunamgonj', 'Sunamgonj'), ('Rajshahi', 'Rajhshahi'), 
                    ('Pabna', 'Pabna'), ('Dinajpur', 'Dinajpur'), ('Kustia', 'Kustia'), ('Barishal', 'Barishal'), ('Narayangonj', 'Narayangonj'), 
                    ('Rangpur', 'Rangpur'), ('Chittagong', 'Chittagong'), ('Khulna', 'Khulna'), ('Jhinaidah', 'Jhinaidah'), ('Josshore', 'Josshore'), 
                    ('Joypurhat', 'Joypurhat'), ('Chandpur', 'Chandpur'), ('Nuakhali', 'Nuakhali'), ('Rangamati', 'Rangamati'), ('Madaripur', 'Madaripur'), 
                    ('Manikgonj', 'Manikgonj'), ('Sylhet', 'Sylhet'), ('Bagherhat', 'Bagherhat'), ('CoxsBazar', 'CoxsBazar'), ('Pirojpur', 'Pirojpur'), 
                    ('Laxmipur', 'Laxmipur'), ('Gaibandha', 'Gaibandha'), ('Kurigram', 'Kurigrham'), ('Kurigram', 'Kurigram')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
